# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d7dea229378eeb61e87819f1054716f1c2ee2293aeea60bdf71922841d4863bc8c8050bc8a51bc9238eacad03ad8b04d1f86fbba6021deb506bb4b6d60237e5

test:
  secret_key_base: a6d1f2f127c48cb9c8b89a67afb881a2add953a9dfe727be5afd2b7dc58e884b7fdf36fa01cef479ccd80c03b63ddc592290c630f55fe2a6dcd2eff016455ddc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
